### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by balena** [neutrino38/elixip#1]
Recently I wrote http://github.com/balena/elixir-sippet and I was looking for other similar source codes to compare, then I found yours. I had a look, but I could not figure out how to use neither if the code is working.

Do you have any quick start documentation?

**Comment by neutrino38** [comment]
Hi,

No it does not work. It is a personal PET project but I did not have the time to invest to make it work. I will look at your work with great pleasure as I firmly believe that Elixir may have a future for telecom apps.

Sorry if I gave you some false hope

**Comment by balena** [comment]
No problem @neutrino38, no worries. So maybe we can collaborate in http://github.com/balena/elixir-sippet. Recently I started a "module" for sippet in http://github.com/balena/elixir-sippet-proxy.

**Comment by neutrino38** [comment]
Sure. I am interested. Not sure when though. What are your plans for this? Do you intend to keep it open source ? I am allowed to embed it into a commercial product ? Let us discuss.

**Comment by balena** [comment]
The Sippet code is complete now, it may receive code updates by now. The Proxy code is quite new and will receive more components soon. I'm using a BSD license on the code, and therefore you may use the sources in commercial products if you want.

**Comment by neutrino38** [comment]
Good. I will try it.
