### ISSUE TITLE
does libbfcp support `BFCP over UDP` on server side 

### ISSUE THREAD

**Issue by TianpingHsu** [neutrino38/elixip#2]
Hi,  @neutrino38 
I find that `BFCP_Server::OpenUdpConnection` does not call `BFCPConnection::connect`, while `BFCP_Server::OpenTcpConnect` does.
so, does libcfcp support `BFCP over UDP` on server side? if it does, how can I use it or should I modify something?
thanks.

P.S. 
I am sorry to ask this question here, it seems that there's no any other good way to contact you. And I am testing BFCP of  [OPAL](http://www.opalvoip.org/) which uses https://github.com/InteractiviteVideoEtSystemes/libbfcp

**Comment by neutrino38** [comment]
Sorry, I am not working anymore on the BFCP_Server project
